apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    workload.user.cattle.io/workloadselector: deployment-dsg-front-dollarsmartglobal-com
  name: dollarsmartglobal-com
  namespace: dsg-front
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-dsg-front-dollarsmartglobal-com
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-dsg-front-dollarsmartglobal-com
    spec:
      containers:
      - image: 589962364545.dkr.ecr.ap-southeast-1.amazonaws.com/dollarsmartglobal-com:1.0.17
        imagePullPolicy: Always
        name: dollarsmartglobal-com
        resources: {}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: aws-ecr-secrets
      restartPolicy: Always
      schedulerName: default-scheduler

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:dsg-front:dollarsmartglobal-com"]'
  name: dollarsmartglobal-com-wl-svc
  namespace: dsg-front
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: deployment-dsg-front-dollarsmartglobal-com
  type: ClusterIP
  
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: dsg-public-lb-1
    cert-manager.io/cluster-issuer: aws-issuer
  name: dollarsmartglobal-com-ingress
  namespace: dsg-front
spec:
  rules:
  - host: dev-www.dollarsmartglobal.com
    http:
      paths:
      - backend:
          serviceName: dollarsmartglobal-com-wl-svc
          servicePort: 80
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - dev-www.dollarsmartglobal.com
    secretName: dsg-www-tls
